### ISSUE TITLE
smart contract transactions

### ISSUE THREAD

**Issue by zlac116** [emesik/cardano-python#15]
Is there a plan to support **smart contract** transactions in this library? thanks

**Comment by emesik** [comment]
Would be great but there's no API in `cardano-wallet` for that and documentation is almost non-existent.

**Comment by zlac116** [comment]
Thanks for the quick response - that's a shame, this woud complete some of the tools that I plan to build...would be nice to have it in one language like python. Do you know if it can be done using the cardano-cli?

**Comment by zlac116** [comment]
Thanks for sharing this resource - will see if I can connect my scripts to run the `cardano-cli`. If you do apply for funding via Catalyst, will definitely vote for the additon of this functionality. Thanks again
