### ISSUE TITLE
Readme to start testing with the real API

### ISSUE THREAD

**Issue by MASalem** [emesik/cardano-python#2]
Hi,

I just wanted to ask for readme explaining the steps to be able to test this API with real data (Explorer API maybe?)

That would help discover bugs certainly, in addition to potential optimisations to do.

Thanks !

**Comment by emesik** [comment]
Docs for 0.1 are exactly what I'm working on currently. Should appear within the next couple of days.

**Comment by MASalem** [comment]
Thanks for documenting
I will close this issue as it is completed.
