### ISSUE TITLE
Metadata Support

### ISSUE THREAD

**Issue by rumourscape** [emesik/cardano-python#3]
Hi,
I would like to know the ETA for Metadata support.
You are doing great work by the way!
Thank you.

**Comment by emesik** [comment]
It should be done today but unfortunately it won't. I had personal issues which distracted me from work over last couple of days. I will reassess the timeline but please expect about a week of delay.

**Comment by rumourscape** [comment]
Oh, it's alright. I am in no hurry. 
Your module is gonna be quite helpful for the project I am planning to propose for Fund 5.
