### ISSUE TITLE
Immutable dicts and lists to be used as metadata keys

### ISSUE THREAD

**Issue by emesik** [emesik/cardano-python#5]
Cardano metadata allows maps (`dict` in Python) to be used as keys for another map. Lists probably could be used too. The official example demonstrates that: https://github.com/input-output-hk/cardano-node/blob/master/doc/reference/tx-metadata.md#detailed-schema

In Python both these objects are mutable, which means they cannot implement `__hash__` method which is necessary for object to act as a key.

The question is how to implement such exceptional use in Python. The preliminary idea is:
1. If `list` is a key, make it `tuple`.
2. For maps implement a `dict` subclass that throws exception on `__setitem__()`, like presented here: https://stackoverflow.com/questions/1151658/python-hashable-dicts

**Comment by rumourscape** [comment]
I tried to use metadata in wal.transfer() but I got a TypeError: transfer() got an unexpected keyword argument 'metadata'
Do you know why this could be?

**Comment by emesik** [comment]
@rumourscape could you provide full traceback?

**Comment by rumourscape** [comment]
Unfortunately that's only error I am getting. I will send you an email with my code.

**Comment by emesik** [comment]
Hmm, the code you sent me works, just needed only to replace metadata key with integer. The resulting tx [is on the blockchain](https://explorer.cardano-testnet.iohkdev.io/en/transaction?id=a8d23443a5928af801ac9d2895acbdd32d42e2de4132c7a89fe8d83257f0f76a).

Anyway, it's a topic for another issue.

**Comment by emesik** [comment]
Fixed in v0.4.2
